// source: protobuf-checkout/nanopb/generator/proto/nanopb.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

import jspb from 'google-protobuf'
var goog = jspb;
var global = Function('return this')();

import google_protobuf_descriptor_pb from 'google-protobuf/google/protobuf/descriptor_pb.js'
goog.object.extend(proto, google_protobuf_descriptor_pb);
goog.exportSymbol('proto.DescriptorSize', null, global);
goog.exportSymbol('proto.FieldType', null, global);
goog.exportSymbol('proto.IntSize', null, global);
goog.exportSymbol('proto.NanoPBOptions', null, global);
goog.exportSymbol('proto.TypenameMangling', null, global);
goog.exportSymbol('proto.nanopb', null, global);
goog.exportSymbol('proto.nanopbEnumopt', null, global);
goog.exportSymbol('proto.nanopbFileopt', null, global);
goog.exportSymbol('proto.nanopbMsgopt', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.NanoPBOptions = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.NanoPBOptions.repeatedFields_, null);
};
goog.inherits(proto.NanoPBOptions, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.NanoPBOptions.displayName = 'proto.NanoPBOptions';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.NanoPBOptions.repeatedFields_ = [24,26];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.NanoPBOptions.prototype.toObject = function(opt_includeInstance) {
  return proto.NanoPBOptions.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.NanoPBOptions} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.NanoPBOptions.toObject = function(includeInstance, msg) {
  var f, obj = {
    maxSize: (f = jspb.Message.getField(msg, 1)) == null ? undefined : f,
    maxLength: (f = jspb.Message.getField(msg, 14)) == null ? undefined : f,
    maxCount: (f = jspb.Message.getField(msg, 2)) == null ? undefined : f,
    intSize: jspb.Message.getFieldWithDefault(msg, 7, 0),
    type: jspb.Message.getFieldWithDefault(msg, 3, 0),
    longNames: jspb.Message.getBooleanFieldWithDefault(msg, 4, true),
    packedStruct: jspb.Message.getBooleanFieldWithDefault(msg, 5, false),
    packedEnum: jspb.Message.getBooleanFieldWithDefault(msg, 10, false),
    skipMessage: jspb.Message.getBooleanFieldWithDefault(msg, 6, false),
    noUnions: jspb.Message.getBooleanFieldWithDefault(msg, 8, false),
    msgid: (f = jspb.Message.getField(msg, 9)) == null ? undefined : f,
    anonymousOneof: jspb.Message.getBooleanFieldWithDefault(msg, 11, false),
    proto3: jspb.Message.getBooleanFieldWithDefault(msg, 12, false),
    proto3SingularMsgs: jspb.Message.getBooleanFieldWithDefault(msg, 21, false),
    enumToString: jspb.Message.getBooleanFieldWithDefault(msg, 13, false),
    fixedLength: jspb.Message.getBooleanFieldWithDefault(msg, 15, false),
    fixedCount: jspb.Message.getBooleanFieldWithDefault(msg, 16, false),
    submsgCallback: jspb.Message.getBooleanFieldWithDefault(msg, 22, false),
    mangleNames: jspb.Message.getFieldWithDefault(msg, 17, 0),
    callbackDatatype: jspb.Message.getFieldWithDefault(msg, 18, "pb_callback_t"),
    callbackFunction: jspb.Message.getFieldWithDefault(msg, 19, "pb_default_field_callback"),
    descriptorsize: jspb.Message.getFieldWithDefault(msg, 20, 0),
    defaultHas: jspb.Message.getBooleanFieldWithDefault(msg, 23, false),
    includeList: (f = jspb.Message.getRepeatedField(msg, 24)) == null ? undefined : f,
    excludeList: (f = jspb.Message.getRepeatedField(msg, 26)) == null ? undefined : f,
    pb_package: (f = jspb.Message.getField(msg, 25)) == null ? undefined : f,
    typeOverride: (f = jspb.Message.getField(msg, 27)) == null ? undefined : f,
    sortByTag: jspb.Message.getBooleanFieldWithDefault(msg, 28, true)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.NanoPBOptions}
 */
proto.NanoPBOptions.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.NanoPBOptions;
  return proto.NanoPBOptions.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.NanoPBOptions} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.NanoPBOptions}
 */
proto.NanoPBOptions.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setMaxSize(value);
      break;
    case 14:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setMaxLength(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setMaxCount(value);
      break;
    case 7:
      var value = /** @type {!proto.IntSize} */ (reader.readEnum());
      msg.setIntSize(value);
      break;
    case 3:
      var value = /** @type {!proto.FieldType} */ (reader.readEnum());
      msg.setType(value);
      break;
    case 4:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setLongNames(value);
      break;
    case 5:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setPackedStruct(value);
      break;
    case 10:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setPackedEnum(value);
      break;
    case 6:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setSkipMessage(value);
      break;
    case 8:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setNoUnions(value);
      break;
    case 9:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setMsgid(value);
      break;
    case 11:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setAnonymousOneof(value);
      break;
    case 12:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setProto3(value);
      break;
    case 21:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setProto3SingularMsgs(value);
      break;
    case 13:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setEnumToString(value);
      break;
    case 15:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setFixedLength(value);
      break;
    case 16:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setFixedCount(value);
      break;
    case 22:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setSubmsgCallback(value);
      break;
    case 17:
      var value = /** @type {!proto.TypenameMangling} */ (reader.readEnum());
      msg.setMangleNames(value);
      break;
    case 18:
      var value = /** @type {string} */ (reader.readString());
      msg.setCallbackDatatype(value);
      break;
    case 19:
      var value = /** @type {string} */ (reader.readString());
      msg.setCallbackFunction(value);
      break;
    case 20:
      var value = /** @type {!proto.DescriptorSize} */ (reader.readEnum());
      msg.setDescriptorsize(value);
      break;
    case 23:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setDefaultHas(value);
      break;
    case 24:
      var value = /** @type {string} */ (reader.readString());
      msg.addInclude(value);
      break;
    case 26:
      var value = /** @type {string} */ (reader.readString());
      msg.addExclude(value);
      break;
    case 25:
      var value = /** @type {string} */ (reader.readString());
      msg.setPackage(value);
      break;
    case 27:
      var value = /** @type {!proto.google.protobuf.FieldDescriptorProto.Type} */ (reader.readEnum());
      msg.setTypeOverride(value);
      break;
    case 28:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setSortByTag(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.NanoPBOptions.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.NanoPBOptions.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.NanoPBOptions} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.NanoPBOptions.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = /** @type {number} */ (jspb.Message.getField(message, 1));
  if (f != null) {
    writer.writeInt32(
      1,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 14));
  if (f != null) {
    writer.writeInt32(
      14,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 2));
  if (f != null) {
    writer.writeInt32(
      2,
      f
    );
  }
  f = /** @type {!proto.IntSize} */ (jspb.Message.getField(message, 7));
  if (f != null) {
    writer.writeEnum(
      7,
      f
    );
  }
  f = /** @type {!proto.FieldType} */ (jspb.Message.getField(message, 3));
  if (f != null) {
    writer.writeEnum(
      3,
      f
    );
  }
  f = /** @type {boolean} */ (jspb.Message.getField(message, 4));
  if (f != null) {
    writer.writeBool(
      4,
      f
    );
  }
  f = /** @type {boolean} */ (jspb.Message.getField(message, 5));
  if (f != null) {
    writer.writeBool(
      5,
      f
    );
  }
  f = /** @type {boolean} */ (jspb.Message.getField(message, 10));
  if (f != null) {
    writer.writeBool(
      10,
      f
    );
  }
  f = /** @type {boolean} */ (jspb.Message.getField(message, 6));
  if (f != null) {
    writer.writeBool(
      6,
      f
    );
  }
  f = /** @type {boolean} */ (jspb.Message.getField(message, 8));
  if (f != null) {
    writer.writeBool(
      8,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 9));
  if (f != null) {
    writer.writeUint32(
      9,
      f
    );
  }
  f = /** @type {boolean} */ (jspb.Message.getField(message, 11));
  if (f != null) {
    writer.writeBool(
      11,
      f
    );
  }
  f = /** @type {boolean} */ (jspb.Message.getField(message, 12));
  if (f != null) {
    writer.writeBool(
      12,
      f
    );
  }
  f = /** @type {boolean} */ (jspb.Message.getField(message, 21));
  if (f != null) {
    writer.writeBool(
      21,
      f
    );
  }
  f = /** @type {boolean} */ (jspb.Message.getField(message, 13));
  if (f != null) {
    writer.writeBool(
      13,
      f
    );
  }
  f = /** @type {boolean} */ (jspb.Message.getField(message, 15));
  if (f != null) {
    writer.writeBool(
      15,
      f
    );
  }
  f = /** @type {boolean} */ (jspb.Message.getField(message, 16));
  if (f != null) {
    writer.writeBool(
      16,
      f
    );
  }
  f = /** @type {boolean} */ (jspb.Message.getField(message, 22));
  if (f != null) {
    writer.writeBool(
      22,
      f
    );
  }
  f = /** @type {!proto.TypenameMangling} */ (jspb.Message.getField(message, 17));
  if (f != null) {
    writer.writeEnum(
      17,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 18));
  if (f != null) {
    writer.writeString(
      18,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 19));
  if (f != null) {
    writer.writeString(
      19,
      f
    );
  }
  f = /** @type {!proto.DescriptorSize} */ (jspb.Message.getField(message, 20));
  if (f != null) {
    writer.writeEnum(
      20,
      f
    );
  }
  f = /** @type {boolean} */ (jspb.Message.getField(message, 23));
  if (f != null) {
    writer.writeBool(
      23,
      f
    );
  }
  f = message.getIncludeList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      24,
      f
    );
  }
  f = message.getExcludeList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      26,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 25));
  if (f != null) {
    writer.writeString(
      25,
      f
    );
  }
  f = /** @type {!proto.google.protobuf.FieldDescriptorProto.Type} */ (jspb.Message.getField(message, 27));
  if (f != null) {
    writer.writeEnum(
      27,
      f
    );
  }
  f = /** @type {boolean} */ (jspb.Message.getField(message, 28));
  if (f != null) {
    writer.writeBool(
      28,
      f
    );
  }
};


/**
 * optional int32 max_size = 1;
 * @return {number}
 */
proto.NanoPBOptions.prototype.getMaxSize = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.NanoPBOptions} returns this
 */
proto.NanoPBOptions.prototype.setMaxSize = function(value) {
  return jspb.Message.setField(this, 1, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.NanoPBOptions} returns this
 */
proto.NanoPBOptions.prototype.clearMaxSize = function() {
  return jspb.Message.setField(this, 1, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.NanoPBOptions.prototype.hasMaxSize = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional int32 max_length = 14;
 * @return {number}
 */
proto.NanoPBOptions.prototype.getMaxLength = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 14, 0));
};


/**
 * @param {number} value
 * @return {!proto.NanoPBOptions} returns this
 */
proto.NanoPBOptions.prototype.setMaxLength = function(value) {
  return jspb.Message.setField(this, 14, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.NanoPBOptions} returns this
 */
proto.NanoPBOptions.prototype.clearMaxLength = function() {
  return jspb.Message.setField(this, 14, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.NanoPBOptions.prototype.hasMaxLength = function() {
  return jspb.Message.getField(this, 14) != null;
};


/**
 * optional int32 max_count = 2;
 * @return {number}
 */
proto.NanoPBOptions.prototype.getMaxCount = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.NanoPBOptions} returns this
 */
proto.NanoPBOptions.prototype.setMaxCount = function(value) {
  return jspb.Message.setField(this, 2, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.NanoPBOptions} returns this
 */
proto.NanoPBOptions.prototype.clearMaxCount = function() {
  return jspb.Message.setField(this, 2, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.NanoPBOptions.prototype.hasMaxCount = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional IntSize int_size = 7;
 * @return {!proto.IntSize}
 */
proto.NanoPBOptions.prototype.getIntSize = function() {
  return /** @type {!proto.IntSize} */ (jspb.Message.getFieldWithDefault(this, 7, 0));
};


/**
 * @param {!proto.IntSize} value
 * @return {!proto.NanoPBOptions} returns this
 */
proto.NanoPBOptions.prototype.setIntSize = function(value) {
  return jspb.Message.setField(this, 7, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.NanoPBOptions} returns this
 */
proto.NanoPBOptions.prototype.clearIntSize = function() {
  return jspb.Message.setField(this, 7, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.NanoPBOptions.prototype.hasIntSize = function() {
  return jspb.Message.getField(this, 7) != null;
};


/**
 * optional FieldType type = 3;
 * @return {!proto.FieldType}
 */
proto.NanoPBOptions.prototype.getType = function() {
  return /** @type {!proto.FieldType} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {!proto.FieldType} value
 * @return {!proto.NanoPBOptions} returns this
 */
proto.NanoPBOptions.prototype.setType = function(value) {
  return jspb.Message.setField(this, 3, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.NanoPBOptions} returns this
 */
proto.NanoPBOptions.prototype.clearType = function() {
  return jspb.Message.setField(this, 3, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.NanoPBOptions.prototype.hasType = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional bool long_names = 4;
 * @return {boolean}
 */
proto.NanoPBOptions.prototype.getLongNames = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 4, true));
};


/**
 * @param {boolean} value
 * @return {!proto.NanoPBOptions} returns this
 */
proto.NanoPBOptions.prototype.setLongNames = function(value) {
  return jspb.Message.setField(this, 4, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.NanoPBOptions} returns this
 */
proto.NanoPBOptions.prototype.clearLongNames = function() {
  return jspb.Message.setField(this, 4, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.NanoPBOptions.prototype.hasLongNames = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional bool packed_struct = 5;
 * @return {boolean}
 */
proto.NanoPBOptions.prototype.getPackedStruct = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 5, false));
};


/**
 * @param {boolean} value
 * @return {!proto.NanoPBOptions} returns this
 */
proto.NanoPBOptions.prototype.setPackedStruct = function(value) {
  return jspb.Message.setField(this, 5, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.NanoPBOptions} returns this
 */
proto.NanoPBOptions.prototype.clearPackedStruct = function() {
  return jspb.Message.setField(this, 5, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.NanoPBOptions.prototype.hasPackedStruct = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * optional bool packed_enum = 10;
 * @return {boolean}
 */
proto.NanoPBOptions.prototype.getPackedEnum = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 10, false));
};


/**
 * @param {boolean} value
 * @return {!proto.NanoPBOptions} returns this
 */
proto.NanoPBOptions.prototype.setPackedEnum = function(value) {
  return jspb.Message.setField(this, 10, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.NanoPBOptions} returns this
 */
proto.NanoPBOptions.prototype.clearPackedEnum = function() {
  return jspb.Message.setField(this, 10, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.NanoPBOptions.prototype.hasPackedEnum = function() {
  return jspb.Message.getField(this, 10) != null;
};


/**
 * optional bool skip_message = 6;
 * @return {boolean}
 */
proto.NanoPBOptions.prototype.getSkipMessage = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 6, false));
};


/**
 * @param {boolean} value
 * @return {!proto.NanoPBOptions} returns this
 */
proto.NanoPBOptions.prototype.setSkipMessage = function(value) {
  return jspb.Message.setField(this, 6, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.NanoPBOptions} returns this
 */
proto.NanoPBOptions.prototype.clearSkipMessage = function() {
  return jspb.Message.setField(this, 6, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.NanoPBOptions.prototype.hasSkipMessage = function() {
  return jspb.Message.getField(this, 6) != null;
};


/**
 * optional bool no_unions = 8;
 * @return {boolean}
 */
proto.NanoPBOptions.prototype.getNoUnions = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 8, false));
};


/**
 * @param {boolean} value
 * @return {!proto.NanoPBOptions} returns this
 */
proto.NanoPBOptions.prototype.setNoUnions = function(value) {
  return jspb.Message.setField(this, 8, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.NanoPBOptions} returns this
 */
proto.NanoPBOptions.prototype.clearNoUnions = function() {
  return jspb.Message.setField(this, 8, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.NanoPBOptions.prototype.hasNoUnions = function() {
  return jspb.Message.getField(this, 8) != null;
};


/**
 * optional uint32 msgid = 9;
 * @return {number}
 */
proto.NanoPBOptions.prototype.getMsgid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 9, 0));
};


/**
 * @param {number} value
 * @return {!proto.NanoPBOptions} returns this
 */
proto.NanoPBOptions.prototype.setMsgid = function(value) {
  return jspb.Message.setField(this, 9, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.NanoPBOptions} returns this
 */
proto.NanoPBOptions.prototype.clearMsgid = function() {
  return jspb.Message.setField(this, 9, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.NanoPBOptions.prototype.hasMsgid = function() {
  return jspb.Message.getField(this, 9) != null;
};


/**
 * optional bool anonymous_oneof = 11;
 * @return {boolean}
 */
proto.NanoPBOptions.prototype.getAnonymousOneof = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 11, false));
};


/**
 * @param {boolean} value
 * @return {!proto.NanoPBOptions} returns this
 */
proto.NanoPBOptions.prototype.setAnonymousOneof = function(value) {
  return jspb.Message.setField(this, 11, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.NanoPBOptions} returns this
 */
proto.NanoPBOptions.prototype.clearAnonymousOneof = function() {
  return jspb.Message.setField(this, 11, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.NanoPBOptions.prototype.hasAnonymousOneof = function() {
  return jspb.Message.getField(this, 11) != null;
};


/**
 * optional bool proto3 = 12;
 * @return {boolean}
 */
proto.NanoPBOptions.prototype.getProto3 = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 12, false));
};


/**
 * @param {boolean} value
 * @return {!proto.NanoPBOptions} returns this
 */
proto.NanoPBOptions.prototype.setProto3 = function(value) {
  return jspb.Message.setField(this, 12, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.NanoPBOptions} returns this
 */
proto.NanoPBOptions.prototype.clearProto3 = function() {
  return jspb.Message.setField(this, 12, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.NanoPBOptions.prototype.hasProto3 = function() {
  return jspb.Message.getField(this, 12) != null;
};


/**
 * optional bool proto3_singular_msgs = 21;
 * @return {boolean}
 */
proto.NanoPBOptions.prototype.getProto3SingularMsgs = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 21, false));
};


/**
 * @param {boolean} value
 * @return {!proto.NanoPBOptions} returns this
 */
proto.NanoPBOptions.prototype.setProto3SingularMsgs = function(value) {
  return jspb.Message.setField(this, 21, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.NanoPBOptions} returns this
 */
proto.NanoPBOptions.prototype.clearProto3SingularMsgs = function() {
  return jspb.Message.setField(this, 21, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.NanoPBOptions.prototype.hasProto3SingularMsgs = function() {
  return jspb.Message.getField(this, 21) != null;
};


/**
 * optional bool enum_to_string = 13;
 * @return {boolean}
 */
proto.NanoPBOptions.prototype.getEnumToString = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 13, false));
};


/**
 * @param {boolean} value
 * @return {!proto.NanoPBOptions} returns this
 */
proto.NanoPBOptions.prototype.setEnumToString = function(value) {
  return jspb.Message.setField(this, 13, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.NanoPBOptions} returns this
 */
proto.NanoPBOptions.prototype.clearEnumToString = function() {
  return jspb.Message.setField(this, 13, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.NanoPBOptions.prototype.hasEnumToString = function() {
  return jspb.Message.getField(this, 13) != null;
};


/**
 * optional bool fixed_length = 15;
 * @return {boolean}
 */
proto.NanoPBOptions.prototype.getFixedLength = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 15, false));
};


/**
 * @param {boolean} value
 * @return {!proto.NanoPBOptions} returns this
 */
proto.NanoPBOptions.prototype.setFixedLength = function(value) {
  return jspb.Message.setField(this, 15, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.NanoPBOptions} returns this
 */
proto.NanoPBOptions.prototype.clearFixedLength = function() {
  return jspb.Message.setField(this, 15, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.NanoPBOptions.prototype.hasFixedLength = function() {
  return jspb.Message.getField(this, 15) != null;
};


/**
 * optional bool fixed_count = 16;
 * @return {boolean}
 */
proto.NanoPBOptions.prototype.getFixedCount = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 16, false));
};


/**
 * @param {boolean} value
 * @return {!proto.NanoPBOptions} returns this
 */
proto.NanoPBOptions.prototype.setFixedCount = function(value) {
  return jspb.Message.setField(this, 16, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.NanoPBOptions} returns this
 */
proto.NanoPBOptions.prototype.clearFixedCount = function() {
  return jspb.Message.setField(this, 16, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.NanoPBOptions.prototype.hasFixedCount = function() {
  return jspb.Message.getField(this, 16) != null;
};


/**
 * optional bool submsg_callback = 22;
 * @return {boolean}
 */
proto.NanoPBOptions.prototype.getSubmsgCallback = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 22, false));
};


/**
 * @param {boolean} value
 * @return {!proto.NanoPBOptions} returns this
 */
proto.NanoPBOptions.prototype.setSubmsgCallback = function(value) {
  return jspb.Message.setField(this, 22, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.NanoPBOptions} returns this
 */
proto.NanoPBOptions.prototype.clearSubmsgCallback = function() {
  return jspb.Message.setField(this, 22, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.NanoPBOptions.prototype.hasSubmsgCallback = function() {
  return jspb.Message.getField(this, 22) != null;
};


/**
 * optional TypenameMangling mangle_names = 17;
 * @return {!proto.TypenameMangling}
 */
proto.NanoPBOptions.prototype.getMangleNames = function() {
  return /** @type {!proto.TypenameMangling} */ (jspb.Message.getFieldWithDefault(this, 17, 0));
};


/**
 * @param {!proto.TypenameMangling} value
 * @return {!proto.NanoPBOptions} returns this
 */
proto.NanoPBOptions.prototype.setMangleNames = function(value) {
  return jspb.Message.setField(this, 17, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.NanoPBOptions} returns this
 */
proto.NanoPBOptions.prototype.clearMangleNames = function() {
  return jspb.Message.setField(this, 17, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.NanoPBOptions.prototype.hasMangleNames = function() {
  return jspb.Message.getField(this, 17) != null;
};


/**
 * optional string callback_datatype = 18;
 * @return {string}
 */
proto.NanoPBOptions.prototype.getCallbackDatatype = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 18, "pb_callback_t"));
};


/**
 * @param {string} value
 * @return {!proto.NanoPBOptions} returns this
 */
proto.NanoPBOptions.prototype.setCallbackDatatype = function(value) {
  return jspb.Message.setField(this, 18, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.NanoPBOptions} returns this
 */
proto.NanoPBOptions.prototype.clearCallbackDatatype = function() {
  return jspb.Message.setField(this, 18, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.NanoPBOptions.prototype.hasCallbackDatatype = function() {
  return jspb.Message.getField(this, 18) != null;
};


/**
 * optional string callback_function = 19;
 * @return {string}
 */
proto.NanoPBOptions.prototype.getCallbackFunction = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 19, "pb_default_field_callback"));
};


/**
 * @param {string} value
 * @return {!proto.NanoPBOptions} returns this
 */
proto.NanoPBOptions.prototype.setCallbackFunction = function(value) {
  return jspb.Message.setField(this, 19, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.NanoPBOptions} returns this
 */
proto.NanoPBOptions.prototype.clearCallbackFunction = function() {
  return jspb.Message.setField(this, 19, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.NanoPBOptions.prototype.hasCallbackFunction = function() {
  return jspb.Message.getField(this, 19) != null;
};


/**
 * optional DescriptorSize descriptorsize = 20;
 * @return {!proto.DescriptorSize}
 */
proto.NanoPBOptions.prototype.getDescriptorsize = function() {
  return /** @type {!proto.DescriptorSize} */ (jspb.Message.getFieldWithDefault(this, 20, 0));
};


/**
 * @param {!proto.DescriptorSize} value
 * @return {!proto.NanoPBOptions} returns this
 */
proto.NanoPBOptions.prototype.setDescriptorsize = function(value) {
  return jspb.Message.setField(this, 20, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.NanoPBOptions} returns this
 */
proto.NanoPBOptions.prototype.clearDescriptorsize = function() {
  return jspb.Message.setField(this, 20, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.NanoPBOptions.prototype.hasDescriptorsize = function() {
  return jspb.Message.getField(this, 20) != null;
};


/**
 * optional bool default_has = 23;
 * @return {boolean}
 */
proto.NanoPBOptions.prototype.getDefaultHas = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 23, false));
};


/**
 * @param {boolean} value
 * @return {!proto.NanoPBOptions} returns this
 */
proto.NanoPBOptions.prototype.setDefaultHas = function(value) {
  return jspb.Message.setField(this, 23, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.NanoPBOptions} returns this
 */
proto.NanoPBOptions.prototype.clearDefaultHas = function() {
  return jspb.Message.setField(this, 23, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.NanoPBOptions.prototype.hasDefaultHas = function() {
  return jspb.Message.getField(this, 23) != null;
};


/**
 * repeated string include = 24;
 * @return {!Array<string>}
 */
proto.NanoPBOptions.prototype.getIncludeList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 24));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.NanoPBOptions} returns this
 */
proto.NanoPBOptions.prototype.setIncludeList = function(value) {
  return jspb.Message.setField(this, 24, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.NanoPBOptions} returns this
 */
proto.NanoPBOptions.prototype.addInclude = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 24, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.NanoPBOptions} returns this
 */
proto.NanoPBOptions.prototype.clearIncludeList = function() {
  return this.setIncludeList([]);
};


/**
 * repeated string exclude = 26;
 * @return {!Array<string>}
 */
proto.NanoPBOptions.prototype.getExcludeList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 26));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.NanoPBOptions} returns this
 */
proto.NanoPBOptions.prototype.setExcludeList = function(value) {
  return jspb.Message.setField(this, 26, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.NanoPBOptions} returns this
 */
proto.NanoPBOptions.prototype.addExclude = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 26, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.NanoPBOptions} returns this
 */
proto.NanoPBOptions.prototype.clearExcludeList = function() {
  return this.setExcludeList([]);
};


/**
 * optional string package = 25;
 * @return {string}
 */
proto.NanoPBOptions.prototype.getPackage = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 25, ""));
};


/**
 * @param {string} value
 * @return {!proto.NanoPBOptions} returns this
 */
proto.NanoPBOptions.prototype.setPackage = function(value) {
  return jspb.Message.setField(this, 25, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.NanoPBOptions} returns this
 */
proto.NanoPBOptions.prototype.clearPackage = function() {
  return jspb.Message.setField(this, 25, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.NanoPBOptions.prototype.hasPackage = function() {
  return jspb.Message.getField(this, 25) != null;
};


/**
 * optional google.protobuf.FieldDescriptorProto.Type type_override = 27;
 * @return {!proto.google.protobuf.FieldDescriptorProto.Type}
 */
proto.NanoPBOptions.prototype.getTypeOverride = function() {
  return /** @type {!proto.google.protobuf.FieldDescriptorProto.Type} */ (jspb.Message.getFieldWithDefault(this, 27, 1));
};


/**
 * @param {!proto.google.protobuf.FieldDescriptorProto.Type} value
 * @return {!proto.NanoPBOptions} returns this
 */
proto.NanoPBOptions.prototype.setTypeOverride = function(value) {
  return jspb.Message.setField(this, 27, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.NanoPBOptions} returns this
 */
proto.NanoPBOptions.prototype.clearTypeOverride = function() {
  return jspb.Message.setField(this, 27, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.NanoPBOptions.prototype.hasTypeOverride = function() {
  return jspb.Message.getField(this, 27) != null;
};


/**
 * optional bool sort_by_tag = 28;
 * @return {boolean}
 */
proto.NanoPBOptions.prototype.getSortByTag = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 28, true));
};


/**
 * @param {boolean} value
 * @return {!proto.NanoPBOptions} returns this
 */
proto.NanoPBOptions.prototype.setSortByTag = function(value) {
  return jspb.Message.setField(this, 28, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.NanoPBOptions} returns this
 */
proto.NanoPBOptions.prototype.clearSortByTag = function() {
  return jspb.Message.setField(this, 28, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.NanoPBOptions.prototype.hasSortByTag = function() {
  return jspb.Message.getField(this, 28) != null;
};


/**
 * @enum {number}
 */
proto.FieldType = {
  FT_DEFAULT: 0,
  FT_CALLBACK: 1,
  FT_POINTER: 4,
  FT_STATIC: 2,
  FT_IGNORE: 3,
  FT_INLINE: 5
};

/**
 * @enum {number}
 */
proto.IntSize = {
  IS_DEFAULT: 0,
  IS_8: 8,
  IS_16: 16,
  IS_32: 32,
  IS_64: 64
};

/**
 * @enum {number}
 */
proto.TypenameMangling = {
  M_NONE: 0,
  M_STRIP_PACKAGE: 1,
  M_FLATTEN: 2,
  M_PACKAGE_INITIALS: 3
};

/**
 * @enum {number}
 */
proto.DescriptorSize = {
  DS_AUTO: 0,
  DS_1: 1,
  DS_2: 2,
  DS_4: 4,
  DS_8: 8
};


/**
 * A tuple of {field number, class constructor} for the extension
 * field named `nanopbFileopt`.
 * @type {!jspb.ExtensionFieldInfo<!proto.NanoPBOptions>}
 */
proto.nanopbFileopt = new jspb.ExtensionFieldInfo(
    1010,
    {nanopbFileopt: 0},
    proto.NanoPBOptions,
     /** @type {?function((boolean|undefined),!jspb.Message=): !Object} */ (
         proto.NanoPBOptions.toObject),
    0);

google_protobuf_descriptor_pb.FileOptions.extensionsBinary[1010] = new jspb.ExtensionFieldBinaryInfo(
    proto.nanopbFileopt,
    jspb.BinaryReader.prototype.readMessage,
    jspb.BinaryWriter.prototype.writeMessage,
    proto.NanoPBOptions.serializeBinaryToWriter,
    proto.NanoPBOptions.deserializeBinaryFromReader,
    false);
// This registers the extension field with the extended class, so that
// toObject() will function correctly.
google_protobuf_descriptor_pb.FileOptions.extensions[1010] = proto.nanopbFileopt;


/**
 * A tuple of {field number, class constructor} for the extension
 * field named `nanopbMsgopt`.
 * @type {!jspb.ExtensionFieldInfo<!proto.NanoPBOptions>}
 */
proto.nanopbMsgopt = new jspb.ExtensionFieldInfo(
    1010,
    {nanopbMsgopt: 0},
    proto.NanoPBOptions,
     /** @type {?function((boolean|undefined),!jspb.Message=): !Object} */ (
         proto.NanoPBOptions.toObject),
    0);

google_protobuf_descriptor_pb.MessageOptions.extensionsBinary[1010] = new jspb.ExtensionFieldBinaryInfo(
    proto.nanopbMsgopt,
    jspb.BinaryReader.prototype.readMessage,
    jspb.BinaryWriter.prototype.writeMessage,
    proto.NanoPBOptions.serializeBinaryToWriter,
    proto.NanoPBOptions.deserializeBinaryFromReader,
    false);
// This registers the extension field with the extended class, so that
// toObject() will function correctly.
google_protobuf_descriptor_pb.MessageOptions.extensions[1010] = proto.nanopbMsgopt;


/**
 * A tuple of {field number, class constructor} for the extension
 * field named `nanopbEnumopt`.
 * @type {!jspb.ExtensionFieldInfo<!proto.NanoPBOptions>}
 */
proto.nanopbEnumopt = new jspb.ExtensionFieldInfo(
    1010,
    {nanopbEnumopt: 0},
    proto.NanoPBOptions,
     /** @type {?function((boolean|undefined),!jspb.Message=): !Object} */ (
         proto.NanoPBOptions.toObject),
    0);

google_protobuf_descriptor_pb.EnumOptions.extensionsBinary[1010] = new jspb.ExtensionFieldBinaryInfo(
    proto.nanopbEnumopt,
    jspb.BinaryReader.prototype.readMessage,
    jspb.BinaryWriter.prototype.writeMessage,
    proto.NanoPBOptions.serializeBinaryToWriter,
    proto.NanoPBOptions.deserializeBinaryFromReader,
    false);
// This registers the extension field with the extended class, so that
// toObject() will function correctly.
google_protobuf_descriptor_pb.EnumOptions.extensions[1010] = proto.nanopbEnumopt;


/**
 * A tuple of {field number, class constructor} for the extension
 * field named `nanopb`.
 * @type {!jspb.ExtensionFieldInfo<!proto.NanoPBOptions>}
 */
proto.nanopb = new jspb.ExtensionFieldInfo(
    1010,
    {nanopb: 0},
    proto.NanoPBOptions,
     /** @type {?function((boolean|undefined),!jspb.Message=): !Object} */ (
         proto.NanoPBOptions.toObject),
    0);

google_protobuf_descriptor_pb.FieldOptions.extensionsBinary[1010] = new jspb.ExtensionFieldBinaryInfo(
    proto.nanopb,
    jspb.BinaryReader.prototype.readMessage,
    jspb.BinaryWriter.prototype.writeMessage,
    proto.NanoPBOptions.serializeBinaryToWriter,
    proto.NanoPBOptions.deserializeBinaryFromReader,
    false);
// This registers the extension field with the extended class, so that
// toObject() will function correctly.
google_protobuf_descriptor_pb.FieldOptions.extensions[1010] = proto.nanopb;

export default proto
